

name: CI

on: [push, workflow_dispatch]

jobs:

  build:
  
  
    runs-on: windows-latest
    
    
 steps:
 
      - name: Download
        run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHbrok-stable-windows-amd64.zip -OutFile ngrok.zip
        continue-on-error: true

      - name: Extract
        run: Expand-Archive ngrok.zip
        continue-on-error: true

      - name: Auth
        run: .\ngrok\ngrok.exe authtoken $:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        continue-on-error: true

      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        continue-on-error: true

      - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        continue-on-error: true

      - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        continue-on-error: true

      - run: Set-LocalUser -Namerunneradmin" -Password (ConvertTo-SecureString -AsPlainTextP@ssw0rd!" -Force)
        continue-on-error: true

      - name: Create Tunnel
        run: .\ngrok\ngrok.exe tcp 3389
        continue-on-error: true
